import unittest

from unit.test_handler_read_schematic import ReadSchematicHandlerCase
from unit.test_handler_html_sections import HtmlSectionsHandlerCase

from unit.test_handler_string_processes_1 import StringProcesses1HandlerCase
from unit.test_handler_string_processes_2 import StringProcesses2HandlerCase
from unit.test_handler_string_processes_3 import StringProcesses3HandlerCase
from unit.test_handler_string_processes_4 import StringProcesses4HandlerCase
from unit.test_handler_string_processes_5 import StringProcesses5HandlerCase

from unit.test_handler_html_elements_1 import HtmlElements1HandlerCase
from unit.test_handler_html_elements_2 import HtmlElements2HandlerCase
from unit.test_handler_html_elements_3 import HtmlElements3HandlerCase
from unit.test_handler_html_elements_4 import HtmlElements4HandlerCase
from unit.test_handler_html_elements_5 import HtmlElements5HandlerCase
from unit.test_handler_html_elements_6 import HtmlElements6HandlerCase

from unit.test_handler_lists_1 import ListsHandler1Case
from unit.test_handler_lists_2 import ListsHandler2Case
from unit.test_handler_lists_3 import ListsHandler3Case
from unit.test_handler_lists_4 import ListsHandler4Case
from unit.test_handler_lists_5 import ListsHandler5Case

from unit.test_handler_second_processes_1 import SecondProcessesHandler1Case
from unit.test_handler_second_processes_2 import SecondProcessesHandler2Case
from unit.test_handler_second_processes_3 import SecondProcessesHandler3Case

from unit.test_handler_meta_elements import SetMetaElementsCase

from unit.test_handler_classes_1 import ClassesHandler1Case

from unit.test_handler_bucket_file_preparation import BucketFilePreparationHandler1Case

from mockAws.test_handler_bucket_operations import RenderHtmlBucketOperations
from mockAws.test_handler_bucket_operations import CreateListPagesBucketOperations
from mockAws.test_handler_bucket_operations import SearchContentBucketOperations

from mockAws.test_handler_renderHtml_writes import RenderHtmlReadWrites
from mockAws.test_handler_renderHtml_process import RenderHtmlProcess

from mockAws.test_handler_createListPages_writes import CreateListPagesReadWrites
from mockAws.test_handler_createListPages_process import CreateListPagesProcess

from mockAws.test_handler_searchContent_writes import SearchContentReadWrites
from mockAws.test_handler_searchContent_process import SearchContentProcess

def suite():
    suite = unittest.TestSuite()
    return suite

if __name__ == '__main__':
    runner = unittest.TextTestRunner()
    runner.run(suite())
