AWSTemplateFormatVersion: "2010-09-09"
Description: |+
  Morfless Set-up Pre:
    Creates bucket structure separately - This is important if using CloudFront

Parameters:
  morflessS3WebsiteBucket:
    Type: String
    Default: mydomain.com
    Description: The target bucket i.e. website. Dots can be used.
  morflessListBucket:
    Type: String
    Default: morfless-mydomain-list
    Description: The backend list bucket
  morflessSourceBucket:
    Type: String
    Default: morfless-mydomain-source
    Description: The backend source files bucket
  morflessSearchBucket:
    Type: String
    Default: morfless-mydomain-search
    Description: The backend search files bucket

Resources:
  WebsiteBucket:
    Properties:
      BucketName: !Ref morflessS3WebsiteBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    Type: "AWS::S3::Bucket"

  SourceBucket:
    Properties:
      BucketName: !Ref morflessSourceBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Type: "AWS::S3::Bucket"

  SearchBucket:
    Properties:
      BucketName: !Ref morflessSearchBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Type: "AWS::S3::Bucket"

  ListBucket:
    Properties:
      BucketName: !Ref morflessListBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Type: "AWS::S3::Bucket"

  WebsiteBucketPolicy:
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${morflessS3WebsiteBucket}/*"
    Type: "AWS::S3::BucketPolicy"
