---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  MorfLess Clear Buckets

  Clears buckets source, list, search and target to allow tear down of MorfLess deployment stack

Parameters:
  morflessS3WebsiteBucket:
    Type: String
    Default: mydomain.com
    Description: The target bucket i.e. website. Dots can be used.
  morflessListBucket:
    Type: String
    Default: morfless-mydomain-list
    Description: The backend list bucket
  morflessSourceBucket:
    Type: String
    Default: morfless-mydomain-source
    Description: The backend source files bucket
  morflessSearchBucket:
    Type: String
    Default: morfless-mydomain-search
    Description: The backend search files bucket

Resources:
  MorflessBackUpContent:
    Properties:
      ServiceToken: !GetAtt DeleteS3ObjectsFunction.Arn
      TargetBucket: !Ref morflessS3WebsiteBucket
      ListBucket: !Ref morflessListBucket
      SourceBucket: !Ref morflessSourceBucket
      SearchBucket: !Ref morflessSearchBucket
    Type: "Custom::S3Objects"
    DeletionPolicy: Delete

  S3DeleteRole:
    Type: AWS::IAM::Role
    Properties:

      Path: /morfless/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Sid: AllowLogging
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              -
                Sid: SourceBucketDeleteAccess
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub "arn:aws:s3:::${morflessS3WebsiteBucket}"
                  - !Sub "arn:aws:s3:::${morflessS3WebsiteBucket}/*"
                  - !Sub "arn:aws:s3:::${morflessListBucket}"
                  - !Sub "arn:aws:s3:::${morflessListBucket}/*"
                  - !Sub "arn:aws:s3:::${morflessSourceBucket}"
                  - !Sub "arn:aws:s3:::${morflessSourceBucket}/*"
                  - !Sub "arn:aws:s3:::${morflessSearchBucket}"
                  - !Sub "arn:aws:s3:::${morflessSearchBucket}/*"

  DeleteS3ObjectsFunction:
    Properties:
      Description: Deletes objects from a source S3 bucket to a destinations
      Handler: index.handler
      Runtime: python3.7
      Role: !GetAtt S3DeleteRole.Arn
      Timeout: 120
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import urllib3

          http = urllib3.PoolManager()
          s3resource = boto3.resource('s3')
          s3client = boto3.client('s3')

          import logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)


          def handler(event, context):
              logger.info("Received event: %s" % json.dumps(event))

              target_bucket = event['ResourceProperties']['TargetBucket']
              list_bucket = event['ResourceProperties']['ListBucket']
              search_bucket = event['ResourceProperties']['SearchBucket']
              source_files_bucket = event['ResourceProperties']['SourceBucket']

              web_deleted = False
              list_deleted = False
              source_files_deleted = False
              search_deleted = False

              result = 'SUCCESS'

              try:
                  if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':

                      web_deleted = delete_objects(target_bucket)
                      list_deleted = delete_objects(list_bucket)
                      source_files_deleted = delete_objects(source_files_bucket)
                      search_deleted = delete_objects(search_bucket)

                      if web_deleted and list_deleted and source_files_deleted and search_deleted:
                          result = 'SUCCESS'
                      else:
                          result = 'FAILED'

                  elif event['RequestType'] == 'Delete':
                      # don't delete buckets but send a successful response to be able to delete stack
                      result = 'SUCCESS'

              except ClientError as e:
                  logger.error('Error: %s', e)
                  result = 'FAILED'

              cfnresponse_send(event, context, result, {})


          def delete_objects(bucket):

              filelist = []
              deleted = False
              for object in s3client.list_objects(Bucket=bucket)['Contents']:
                  filelist.append(object['Key'])

              if filelist:
                  for file in filelist:
                      s3client.delete_object(
                          Bucket=bucket,
                          Key=file)
                      deleted = True

              return deleted

          # copy of cfnresponse from https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py

          def cfnresponse_send(event, context, responseStatus, responseData, physicalResourceId=None, noEcho=False):

              responseUrl = event['ResponseURL']

              print(responseUrl)

              responseBody = {}
              responseBody['Status'] = responseStatus
              responseBody['Reason'] = 'See the details in CloudWatch Log Stream: ' + context.log_stream_name
              responseBody['PhysicalResourceId'] = physicalResourceId or context.log_stream_name
              responseBody['StackId'] = event['StackId']
              responseBody['RequestId'] = event['RequestId']
              responseBody['LogicalResourceId'] = event['LogicalResourceId']
              responseBody['NoEcho'] = noEcho
              responseBody['Data'] = responseData

              json_responseBody = json.dumps(responseBody)

              print("Response body:\n" + json_responseBody)

              headers = {
                  'content-type' : '',
                  'content-length' : str(len(json_responseBody))
              }

              try:

                  response = http.request('PUT',responseUrl,body=json_responseBody.encode('utf-8'),headers=headers)
                  print("Status code: " + response.reason)
              except Exception as e:
                  print("send(..) failed executing requests.put(..): " + str(e))


    Type: AWS::Lambda::Function
